export const F = "'Oswald', sans-serif";
export const FB = "'Cormorant Garamond', Georgia, serif";

export const S = {
  app: { fontFamily: FB, background: "#fbf0df", color: "#2a0a08", minHeight: "100vh", maxWidth: 600, margin: "0 auto", paddingBottom: 40 },
  loading: { display: "flex", justifyContent: "center", alignItems: "center", height: "100vh" },
  spinner: { width: 32, height: 32, border: "3px solid #d4b898", borderTopColor: "#450206", borderRadius: "50%", animation: "spin 0.8s linear infinite" },
  header: { display: "flex", justifyContent: "space-between", alignItems: "center", padding: "14px 16px", borderBottom: "1px solid #5a1010", position: "sticky", top: 0, background: "#450206", zIndex: 100 },
  headerLeft: { display: "flex", alignItems: "center", gap: 8 },
  title: { fontSize: 17, fontWeight: 700, color: "#ffffff", letterSpacing: "2px", textTransform: "uppercase", fontFamily: FB },
  nav: { display: "flex", gap: 2 },
  navBtn: { background: "none", border: "none", color: "rgba(251,240,223,0.6)", padding: "6px 10px", borderRadius: 8, fontSize: 11, fontWeight: 600, cursor: "pointer", letterSpacing: "1px", textTransform: "uppercase", fontFamily: F },
  navBtnActive: { background: "rgba(0,0,0,0.2)", color: "#ffffff" },
  content: { padding: "16px" },
  section: { marginTop: 24 },
  sectionTitle: { fontSize: 10, fontWeight: 700, color: "#450206", textTransform: "uppercase", letterSpacing: 2.5, margin: 0, marginBottom: 12, fontFamily: F },
  newBtn: { width: "100%", padding: "15px", background: "#450206", color: "#ffffff", border: "none", borderRadius: 24, fontSize: 13, fontWeight: 700, cursor: "pointer", display: "flex", alignItems: "center", justifyContent: "center", gap: 8, letterSpacing: "2px", textTransform: "uppercase", fontFamily: F },
  card: { background: "#f0e0c4", border: "1px solid #d4b898", borderRadius: 10, padding: "14px 16px", marginBottom: 8, cursor: "pointer" },
  cardHeader: { display: "flex", justifyContent: "space-between", alignItems: "center" },
  cardTitle: { fontSize: 16, fontWeight: 600, color: "#2a0a08", letterSpacing: "0.5px" },
  cardSub: { fontSize: 13, color: "#5c3020", marginTop: 2, letterSpacing: "0.5px" },
  cardPot: { fontSize: 15, fontWeight: 700, color: "#450206" },
  liveBadge: { background: "rgba(69,2,6,0.12)", color: "#450206", fontSize: 9, fontWeight: 700, padding: "2px 7px", borderRadius: 3, letterSpacing: 1.5, border: "1px solid rgba(69,2,6,0.3)", textTransform: "uppercase", fontFamily: F },
  sessionHeader: { marginBottom: 16 },
  sessionName: { fontSize: 24, fontWeight: 700, color: "#2a0a08", margin: 0, letterSpacing: "1px" },
  sessionMeta: { fontSize: 11, color: "#7a5030", marginTop: 4, letterSpacing: "0.5px" },
  statsRow: { display: "flex", gap: 10, marginBottom: 16, flexWrap: "wrap" },
  statBox: { flex: 1, background: "#f0e0c4", border: "1px solid #d4b898", borderRadius: 10, padding: "12px 14px", minWidth: 90 },
  statLabel: { fontSize: 9, color: "#7a5030", textTransform: "uppercase", letterSpacing: 1.5, fontFamily: F },
  statValue: { fontSize: 24, fontWeight: 700, color: "#2a0a08", marginTop: 4 },
  actions: { display: "flex", gap: 8, marginBottom: 16, flexWrap: "wrap" },
  actionBtn: { padding: "10px 16px", background: "#450206", color: "#ffffff", border: "none", borderRadius: 24, fontSize: 11, fontWeight: 700, cursor: "pointer", display: "flex", alignItems: "center", gap: 6, letterSpacing: "1.5px", textTransform: "uppercase", fontFamily: F },
  actionBtnAlt: { padding: "10px 14px", background: "#fbf0df", color: "#450206", border: "1px solid #d4b898", borderRadius: 24, fontSize: 11, fontWeight: 600, cursor: "pointer", display: "flex", alignItems: "center", gap: 6, letterSpacing: "1px", textTransform: "uppercase", fontFamily: F },
  table: { background: "#f0e0c4", border: "1px solid #d4b898", borderRadius: 10, overflow: "hidden", fontVariantNumeric: "lining-nums tabular-nums" },
  tableHead: { display: "flex", padding: "10px 14px", fontSize: 9, color: "#7a5030", textTransform: "uppercase", letterSpacing: 1.5, borderBottom: "1px solid #d4b898", fontFamily: F },
  tableRow: { display: "flex", padding: "11px 14px", alignItems: "center", borderBottom: "1px solid rgba(212,184,152,0.6)", fontSize: 15 },
  tableTotal: { display: "flex", padding: "11px 14px", alignItems: "center", fontSize: 15, color: "#2a0a08", background: "rgba(69,2,6,0.06)" },
  tinyBtn: { background: "none", border: "none", cursor: "pointer", padding: 2, opacity: 0.6, display: "inline-flex" },
  iconBtn: { background: "none", border: "none", cursor: "pointer", padding: 4, opacity: 0.5, display: "inline-flex", borderRadius: 4 },
  endBtn: { width: "100%", padding: "14px", background: "none", color: "#c0392b", border: "1px solid rgba(192,57,43,0.35)", borderRadius: 24, fontSize: 11, fontWeight: 700, cursor: "pointer", marginTop: 20, letterSpacing: "2px", textTransform: "uppercase", fontFamily: F },
  empty: { textAlign: "center", padding: "48px 20px" },
  chartCard: { background: "#f0e0c4", border: "1px solid #d4b898", borderRadius: 10, padding: "16px 12px" },
  exportBtn: { width: "100%", padding: "14px", background: "#fbf0df", color: "#450206", border: "1px solid #d4b898", borderRadius: 24, fontSize: 11, fontWeight: 700, cursor: "pointer", display: "flex", alignItems: "center", justifyContent: "center", gap: 8, letterSpacing: "1.5px", textTransform: "uppercase", fontFamily: F },
  summaryCard: { background: "#f0e0c4", border: "1px solid #d4b898", borderRadius: 14, overflow: "hidden" },
  summaryHeader: { display: "flex", alignItems: "center", gap: 12, padding: "20px 20px 0" },
  summaryTitle: { fontSize: 22, fontWeight: 700, color: "#2a0a08", margin: 0, letterSpacing: "1px" },
  summarySub: { fontSize: 11, color: "#7a5030", marginTop: 2, letterSpacing: "0.5px" },
  summaryStatsRow: { display: "flex", gap: 10, padding: "16px 20px", flexWrap: "wrap" },
  summaryStatBox: { flex: 1, background: "rgba(69,2,6,0.06)", border: "1px solid rgba(69,2,6,0.2)", borderRadius: 10, padding: "12px", minWidth: 80, textAlign: "center" },
  summaryStatLabel: { fontSize: 9, color: "#7a5030", textTransform: "uppercase", letterSpacing: 1.5, fontFamily: F },
  summaryStatVal: { fontSize: 26, fontWeight: 700, color: "#2a0a08" },
  summaryTable: { margin: "0 12px", fontVariantNumeric: "lining-nums tabular-nums", fontFeatureSettings: '"lnum", "tnum"' },
  summaryTableHead: { display: "flex", padding: "8px 10px", fontSize: 9, color: "#7a5030", textTransform: "uppercase", letterSpacing: 1.5, borderBottom: "1px solid #d4b898", fontFamily: F },
  summaryTableRow: { display: "flex", padding: "10px 10px", alignItems: "center", fontSize: 15, borderBottom: "1px solid rgba(212,184,152,0.5)" },
  summaryTableTotalRow: { display: "flex", padding: "10px 10px", alignItems: "center", fontSize: 15, color: "#2a0a08", background: "rgba(69,2,6,0.06)", borderRadius: "0 0 8px 8px" },
  overlay: { position: "fixed", top: 0, left: 0, right: 0, bottom: 0, background: "rgba(42,10,8,0.85)", display: "flex", alignItems: "center", justifyContent: "center", zIndex: 200, padding: 20 },
  modal: { background: "#f5e6cc", border: "1px solid #d4b898", borderRadius: 14, padding: 24, width: "100%", maxWidth: 360 },
  modalTitle: { fontSize: 14, fontWeight: 700, color: "#2a0a08", margin: "0 0 16px", letterSpacing: "1.5px", textTransform: "uppercase", fontFamily: F },
  input: { width: "100%", padding: "12px 14px", background: "#fbf0df", border: "1px solid #d4b898", borderRadius: 8, color: "#2a0a08", fontSize: 16, marginBottom: 10, outline: "none", boxSizing: "border-box" },
  select: { width: "100%", padding: "12px 14px", background: "#fbf0df", border: "1px solid #d4b898", borderRadius: 8, color: "#2a0a08", fontSize: 16, marginBottom: 10, outline: "none", boxSizing: "border-box" },
  modalBtn: { width: "100%", padding: "12px", background: "#450206", color: "#ffffff", border: "none", borderRadius: 24, fontSize: 12, fontWeight: 700, cursor: "pointer", letterSpacing: "2px", textTransform: "uppercase", fontFamily: F },
  modalBtnAlt: { width: "100%", padding: "12px", background: "#fbf0df", color: "#450206", border: "1px solid #d4b898", borderRadius: 24, fontSize: 12, fontWeight: 600, cursor: "pointer", letterSpacing: "1px", textTransform: "uppercase", fontFamily: F },
};

if (typeof document !== "undefined") {
  const el = document.createElement("style");
  el.textContent = `@keyframes spin{to{transform:rotate(360deg)}} *{box-sizing:border-box} body{margin:0;background:#fbf0df} .recharts-surface{overflow:visible}`;
  document.head.appendChild(el);
}
